services:
    godot-agent:
        image: godot-agent
        build: .
        environment:
          OPENAI_API_KEY: ${OPENAI_API_KEY}
          DISABLE_ANONYMOUS_METRICS: true
        ports:
          - '8080:8080'
