services:
    godot-agent:
        image: godot-agent
        build: .
        environment:
          OPENAI_API_KEY: /run/secrets/openai_api_key
          DISABLE_ANONYMOUS_METRICS: true
        ports:
          - '8080:8080'
        secrets:
          - openai_api_key
secrets:
  openai_api_key:
    environment: OPENAI_API_KEY
